version: 2
jobs:
  build:
    docker:
      - image: ubuntu:bionic
    working_directory: /src
    steps:
      - run:
        name: Install dependencies
        command: |
          apt-get update
          apt-get install -y \
            build-essential python3.7 uuid-dev iasl git \
            gcc-5 nasm python3-distutils
          apt-get clean
          ln -sf /usr/bin/python3.7 /usr/bin/python
      - run:
        name: Checkout EDK2
        command: |
          git clone https://github.com/tianocore/edk2.git --depth 1
          cd edk2
          git submodule update --init --recursive
      - run:
        name: Compile build tools
        command: |
          make -C BaseTools
          source ./edksetup.sh
      - run:
        name: Build OVMF X64 Debug
        command: |
          build -p OvmfPkg/OvmfPkgX64.dsc -b DEBUG -a X64 -t GCC5
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF.fd
        destination: X64Debug_OVMF.fd
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_CODE.fd
        destination: X64Debug_OVMF_CODE.fd
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/DEBUG_GCC5/FV/OVMF_VARS.fd
        destination: X64Debug_OVMF_VARS.fd
      - run:
        name: Build OVMF X64 Release
        command: |
          build -p OvmfPkg/OvmfPkgX64.dsc -b RELEASE -a X64 -t GCC5
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF.fd
        destination: X64Release_OVMF.fd
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_CODE.fd
        destination: X64Release_OVMF_CODE.fd
      - store_artifacts:
        path: /src/edk2/Build/OvmfX64/RELEASE_GCC5/FV/OVMF_VARS.fd
        destination: X64Release_OVMF_VARS.fd
