version: 2.1
executors:
  build-executor:
    docker:
      - image: retrage/edk2-nightly:latest
    working_directory: /src/edk2
commands:
  ovmf:
    description: "Build OVMF"
    parameters:
      dsc:
        type: string
        default: "X64"
      arch:
        type: string
        default: "X64"
      target:
        type: string
        default: "RELEASE"
    steps:
      - add_ssh_keys:
          fingerprints:
            - "16:27:ac:a5:76:28:2d:36:63:1b:56:4d:eb:df:a6:48"
      - run:
          name: Build OVMF
          command: |
            source ./edksetup.sh
            build -q \
              -p OvmfPkg/OvmfPkg<< parameters.dsc >>.dsc \
              -b << parameters.target >> \
              -a << parameters.arch >> \
              -t GCC5
      - run:
          name: Deploy OVMF
          working_directory: /src/edk2-nightly
          environment:
            SRC: /src/edk2/Build/Ovmf<< parameters.dsc >>/<< parameters.target >>_GCC5/FV
            DST: /src/edk2-nightly/bin/<< parameters.target >><< parameters.dsc >>
          command: |
            cp ${SRC}/OVMF.fd ${DST}_OVMF.fd
            cp ${SRC}/OVMF_CODE.fd ${DST}_OVMF_CODE.fd
            cp ${SRC}/OVMF_VARS.fd ${DST}_OVMF_VARS.fd
            bash deploy.sh
jobs:
  prepare:
    executor: build-executor
    steps:
      - checkout:
          path: /src/edk2-nightly
      - run:
          name: Checkout EDK2
          working_directory: /src
          command: |
            git clone https://github.com/tianocore/edk2.git --depth 1
      - run:
          name: Update submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Compile build tools
          command: |
            make -C BaseTools
      - save_cache:
          key: src-cache-{{ .Revision }}
          paths:
            - /src/edk2
            - /src/edk2-nightly
  ovmf-x64-release:
    executor: build-executor
    steps:
      - restore_cache:
          key: src-cache-{{ .Revision }}
      - ovmf:
          dsc: "X64"
          arch: "X64"
          target: "RELEASE"
  ovmf-x64-debug:
    executor: build-executor
    steps:
      - restore_cache:
          key: src-cache-{{ .Revision }}
      - ovmf:
          dsc: "X64"
          arch: "X64"
          target: "DEBUG"
workflows:
  version: 2.1
  nightly:
    jobs:
      - prepare
      - ovmf-x64-release:
          requires:
            - prepare
      - ovmf-x64-debug:
          requires:
            - prepare
