version: 2.1
executors:
  build-executor:
    docker:
      - image: retrage/edk2-nightly:latest
    working_directory: /src/edk2
commands:
  init:
    description: "Initialize"
    steps:
      - run:
          name: Checkout EDK2
          working_directory: /src
          command: |
            git clone https://github.com/tianocore/edk2.git --depth 1
      - run:
          name: Update submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Compile build tools
          command: |
            make -C BaseTools
  fini:
    description: "Finalize"
    steps:
      - run:
          name: Checkout source code
          working_directory: /src
          command: |
            git clone https://github.com/retrage/edk2-nightly.git
      - run:
          name: Deploy binaries
          working_directory: /src/edk2-nightly
          command: |
            bash deploy.sh
  ovmf:
    description: "Build OVMF"
    parameters:
      dsc:
        type: string
        default: "X64"
      arch:
        type: string
        default: "X64"
      target:
        type: string
        default: "RELEASE"
    steps:
      - run:
          name: Build OVMF
          command: |
            source ./edksetup.sh
            build -q \
              -p OvmfPkg/OvmfPkg<< parameters.dsc >>.dsc \
              -b << parameters.target >> \
              -a << parameters.arch >> \
              -t GCC5
      - run:
          name: Deploy OVMF
          working_directory: /src/edk2-nightly
          environment:
            SRC: /src/edk2/Build/Ovmf<< parameters.dsc >>/<< parameters.target >>_GCC5/FV
            DST: /src/edk2-nightly/bin/<< parameters.target >><< parameters.dsc >>
          command: |
            cp ${SRC}/OVMF.fd ${DST}_OVMF.fd
            cp ${SRC}/OVMF_CODE.fd ${DST}_OVMF_CODE.fd
            cp ${SRC}/OVMF_VARS.fd ${DST}_OVMF_VARS.fd
  shell:
    description: "Build UEFI Shell"
    parameters:
      arch:
        type: string
        default: "X64"
      target:
        type: string
        default: "RELEASE"
      guid:
        type: string
        default: "EA4BB293-2D7F-4456-A681-1F22F42CD0BC"
    steps:
      - run:
          name: Build UEFI Shell
          command: |
            export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
            source ./edksetup.sh
            build -q \
              -p ShellPkg/ShellPkg.dsc \
              -b << parameters.target >> \
              -a << parameters.arch >> \
              -t GCC5
      - run:
          name: Deploy UEFI Shell
          working_directory: /src/edk2-nightly
          environment:
            SRC: /src/edk2/Build/Shell/<< parameters.target >>_GCC5/<< parameters.arch >>
            DST: /src/edk2-nightly/bin/<< parameters.target >><< parameters.arch >>
          command: |
            cp ${SRC}/Shell_<< parameters.guid >>.efi ${DST}_Shell.efi
  arm-virt:
    description: "Build ArmVirt"
    parameters:
      arch:
        type: string
        default: "AARCH64"
      target:
        type: string
        default: "RELEASE"
    steps:
      - run:
          name: Build ArmVirt
          command: |
            export GCC5_AARCH64_PREFIX=aarch64-linux-gnu-
            source ./edksetup.sh
            build -q \
              -p ArmVirtPkg/ArmVirtQemu.dsc \
              -b << parameters.target >> \
              -a << parameters.arch >> \
              -t GCC5
      - run:
          name: Deploy ArmVirt
          working_directory: /src/edk2-nightly
          environment:
            SRC: /src/edk2/Build/ArmVirtQemu-<< parameters.arch>>/<< parameters.target >>_GCC5/FV
            DST: /src/edk2-nightly/bin/<< parameters.target >><< parameters.arch >>
          command: |
            cp ${SRC}/QEMU_EFI.fd ${DST}_QEMU_EFI.fd
            cp ${SRC}/QEMU_VARS.fd ${DST}_QEMU_VARS.fd
jobs:
  build-x64-qemu:
    executor: build-executor
    steps:
      - init
      - ovmf:
          target: "RELEASE"
      - ovmf:
          target: "DEBUG"
      - fini
  build-aarch64-qemu:
    executor: build-executor
    steps:
      - init
      - arm-virt:
          target: "RELEASE"
      - arm-virt:
          target: "DEBUG"
      - fini
  build-x64-shell:
    executor: build-executor
    steps:
      - init
      - shell:
          arch: "X64"
          target: "RELEASE"
      - shell:
          arch: "X64"
          target: "DEBUG"
      - fini
  build-aarch64-shell:
    executor: build-executor
    steps:
      - init
      - shell:
          arch: "AARCH64"
          target: "DEBUG"
      - shell:
          arch: "AARCH64"
          target: "RELEASE"
      - fini
workflows:
  version: 2.1
  commit:
    jobs:
      - build-x64-qemu
      - build-aarch64-qemu
      - build-x64-shell
      - build-aarch64-shell
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build-x64-qemu
      - build-aarch64-qemu
      - build-x64-shell
      - build-aarch64-shell
