version: 2.1
executors:
  build-executor:
    docker:
      - image: retrage/edk2-nightly:latest
    working_directory: /src/edk2
commands:
  ovmf:
    description: "Build OVMF"
    parameters:
      dsc:
        type: string
        default: "OvmfPkg/OvmfPkgX64.dsc"
      arch:
        type: string
        default: "X64"
      target:
        type: string
        default: "RELEASE"
    steps:
      - run:
          name: Build OVMF
          command: |
            source ./edksetup.sh
            build -q -p parameters.dsc -b parameters.target \
              -a parameters.arch -t GCC5
jobs:
  prepare:
    executors: build-executor
    steps:
      - run:
          name: Checkout EDK2
          working_directory: /src
          command: |
            git clone https://github.com/tianocore/edk2.git --depth 1
      - run:
          name: Update submodules
          command: |
            git submodule update --init --recursive
      - run:
          name: Compile build tools
          command: |
            make -C BaseTools
      - save_cache:
        key: src-cache
        paths: /src/edk2
  ovmf-x64-release:
    executors: build-executor
    steps:
      - restore_cache:
        keys: src-cache
      - ovmf:
          - dsc: "OvmfPkg/OvmfPkgX64.dsc"
          - arch: "X64"
          - target: "RELEASE"
  ovmf-x64-debug:
    executors: build-executor
    steps:
      - restore_cache:
        keys: src-cache
      - ovmf:
          - dsc: "OvmfPkg/OvmfPkgX64.dsc"
          - arch: "X64"
          - target: "DEBUG"
workflows:
  version: 2.1
  nightly:
    jobs:
      - prepare
      - ovmf-x64-release:
        requires:
          - prepare
      - ovmf-x64-debug:
        requires:
          - prepare
